anchor_version = "0.17.0"

[provider]
cluster = "mainnet"
wallet = "DePSWB4sds9fprQHDA5Mnn6LGkYH4p329FRNKrZd1DMJ.json"

[programs.mainnet]
draffle = "rafQbXM9VpPV9hr9NqNHuGECBhwNkbLvXt8VS31zbp4"

[programs.devnet]
draffle = "rafQbXM9VpPV9hr9NqNHuGECBhwNkbLvXt8VS31zbp4"

[scripts]
test = "mocha -t 1000000 tests"

[registry]
url = "https://anchor.projectserum.com"